language: python
services:
  - docker
python:
  - "3.7"
install:
  - pip install .
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install twine
script:
  - pytest --cov=fitsmap -vv
after_success:
  - codecov