language: python
services:
  - docker
python:
  - "3.7.9."
install:
  - python -m pip install -r requirements.txt
  - python -m pip install .
  - python -m pip install pytest
  - python -m pip install pytest-cov
  - python -m pip install codecov
  - python -m pip install twine
script:
  - pytest --cov=fitsmap -vv
after_success:
  - codecov